language: node_js
node_js:
  - "node"
  - "lts/*"
  - "4"
before_script:
  - npm install -g mocha
after_script: 
  - npm run lcov && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
