title: LiquidJS
subtitle: "A simple, expressive and safe template engine."
description: "LiquidJS is a simple, expressive and safe Shopify / GitHub Pages compatible template engine in pure JavaScript."
author: Harttle
language:
  - en
  - zh-cn
timezone: UTC

url: https://liquidjs.com
root: /
permalink: news/:year/:month/:day/:title/
relative_link: true
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0
pretty_urls:
  trailing_index: false
  trailing_html: false

theme: navy
skip_render: "api/**/*"
highlight:
  enable: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''

algolia:
  applicationID: 0X19J927JZ
  apiKey: 533161d821384919672e4ce8a39451b3
  indexName: liquidjs
twitter: harttleharttle
github: harttle/liquidjs
oc: liquidjs
